name: Build and Deploy Django Docker Container

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Log in to DockerHub (optional if you need to push)
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 3: Build Docker image
    - name: Build Docker Image
      run: |
        docker build -t my-django-app:latest .

    # Step 4: Run Docker container locally for testing
    - name: Run Docker Container
      env:
        DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      run: |
        docker run -d -p 8000:8000 \
          -e DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY \
          -e DB_PASSWORD=$DB_PASSWORD \
          my-django-app:latest

    # Step 5: (Optional) Push Docker image to DockerHub
    - name: Push Docker Image
      run: |
        docker tag my-django-app:latest my-dockerhub-user/my-django-app:latest
        docker push my-dockerhub-user/my-django-app:latest
